# Generated by Django 5.2.5 on 2026-08-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('pages_processed', models.PositiveIntegerField(default=0)),
                ('records_seen', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='running', max_length=20)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Martyr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('normalized_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('hometown', models.CharField(blank=True, db_index=True, max_length=500)),
                ('birth_text', models.CharField(blank=True, max_length=100)),
                ('death_text', models.CharField(blank=True, max_length=100)),
                ('zone', models.CharField(blank=True, db_index=True, max_length=30)),
                ('grave_row', models.CharField(blank=True, max_length=30)),
                ('grave_number', models.CharField(blank=True, max_length=30)),
                ('source_url', models.URLField(max_length=500)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name', 'source_id'],
                'indexes': [models.Index(fields=['zone', 'grave_row', 'grave_number'], name='memorial_ma_zone_0ebd4b_idx')],
            },
        ),
    ]
