# Generated by Django 5.2.5 on 2026-08-21 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], db_index=True, default='pending', max_length=20)),
                ('ip_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('user_agent', models.CharField(blank=True, editable=False, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('martyr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tributes', to='memorial.martyr')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['martyr', 'status', 'created_at'], name='memorial_tr_martyr__761eae_idx')],
            },
        ),
    ]
