# Generated by Django 5.2.5 on 2026-08-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0002_tribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('x_percent', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('y_percent', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model("memorial", "TourPoint").objects.bulk_create([
                apps.get_model("memorial", "TourPoint")(slug="gate", number=1, title="Cổng chính", description="Điểm mở đầu hành trình, nơi giới thiệu tổng quan nghĩa trang.", x_percent=48, y_percent=82),
                apps.get_model("memorial", "TourPoint")(slug="relief", number=2, title="Hai bức phù điêu", description="Cụm phù điêu ghi dấu tình đoàn kết Việt Nam – Lào.", x_percent=34, y_percent=48),
                apps.get_model("memorial", "TourPoint")(slug="memorial", number=3, title="Nhà tưởng niệm", description="Không gian trung tâm dành cho các đoàn khách dâng hương.", x_percent=49, y_percent=25),
                apps.get_model("memorial", "TourPoint")(slug="zone-a", number=4, title="Khu A", description="Khu an nghỉ của các liệt sĩ.", x_percent=18, y_percent=57),
                apps.get_model("memorial", "TourPoint")(slug="zone-b", number=5, title="Khu B", description="Không gian tưởng niệm tiếp nối với các trục mộ trang nghiêm.", x_percent=83, y_percent=53),
            ]),
            migrations.RunPython.noop,
        ),
    ]
