# Generated by Django 5.2.5 on 2026-08-22 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0003_tourpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview_image', models.FileField(blank=True, upload_to='tour/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình trải nghiệm 360°',
                'verbose_name_plural': 'Cấu hình trải nghiệm 360°',
            },
        ),
    ]
